name: Test

on:
    push:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: ["10", "12", "14"]

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2-beta
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run prepare
            - run: npm test
